# Workflow to compile LaTeX document and attach PDF to releases

name: Compile and Release PDF

# Controls when the workflow will run
on:
  # Triggers the workflow when a release is created
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Inkscape for SVG processing
      - name: Install Inkscape
        run: |
          sudo apt update
          sudo apt install -y inkscape
          which inkscape
          inkscape --version

      # Compile LaTeX document to PDF using XeLaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          os: debian
          compiler: xelatex
          args: -shell-escape
          pre_compile: |
            which inkscape || (apt update && apt install -y inkscape)
            inkscape --version

      # Upload PDF to release assets
      - name: Upload PDF to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./main.pdf
          asset_name: SummaryZoom.pdf
          asset_content_type: application/pdf
