# Wo# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:
  # Triggers the workflow when a release is created
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions needed for the workflow
permissions:
  contents: write
  actions: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallelmpile LaTeX document and attach PDF to releases

name: Compile and Release PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  #push:
  # Triggers the workflow when a release is created
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to prepare the LaTeX files (convert SVG and modify LaTeX)
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Convert SVG to PDF and modify LaTeX to use it directly
      - name: Convert SVG to PDF and prepare LaTeX
        run: |
          sudo apt update
          sudo apt install -y inkscape
          # Convert the SVG to PDF with a simple name
          inkscape --export-type=pdf --export-filename=sty/logo.pdf sty/logo.svg
          ls -la sty/logo.pdf
          # Create a backup of main.tex and modify it to use PDF instead of SVG
          cp main.tex main.tex.bak
          cp main_plain.tex main_plain.tex.bak
          # Replace all includesvg commands with includegraphics, preserving the width parameter
          sed -i 's/\\includesvg\[\([^]]*\)\]{sty\/logo\.svg}/\\includegraphics[\1]{sty\/logo.pdf}/g' main.tex
          sed -i 's/\\includesvg\[\([^]]*\)\]{sty\/logo\.svg}/\\includegraphics[\1]{sty\/logo.pdf}/g' main_plain.tex
          echo "Modified main.tex and main_plain.tex to use PDF instead of SVG"
          echo "Changes made in main.tex:"
          grep -n "includegraphics.*logo" main.tex || echo "No includegraphics found in main.tex"
          echo "Changes made in main_plain.tex:"
          grep -n "includegraphics.*logo" main_plain.tex || echo "No includegraphics found in main_plain.tex"
          echo "Remaining includesvg commands in main.tex:"
          grep -n "includesvg" main.tex || echo "All includesvg commands replaced in main.tex"
          echo "Remaining includesvg commands in main_plain.tex:"
          grep -n "includesvg" main_plain.tex || echo "All includesvg commands replaced in main_plain.tex"

      # Upload prepared files for the compile jobs
      - name: Upload prepared files
        uses: actions/upload-artifact@v4
        with:
          name: prepared-latex-files
          path: |
            main.tex
            main_plain.tex
            sty/
          retention-days: 1
          compression-level: 0

  # Job to compile the LaTeX document
  compile:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      # Download the prepared files
      - name: Download prepared files
        uses: actions/download-artifact@v4
        with:
          name: prepared-latex-files

      # Compile LaTeX document to PDF using XeLaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: xelatex

      # Upload compiled PDF for combination job
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: temp-main-pdf
          path: main.pdf
          retention-days: 1
          compression-level: 0

  # Job to compile the plain LaTeX document (runs in parallel with main compile)
  compile-plain:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      # Download the prepared files
      - name: Download prepared files
        uses: actions/download-artifact@v4
        with:
          name: prepared-latex-files

      # Compile plain LaTeX document to PDF using XeLaTeX
      - name: Compile plain LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main_plain.tex
          compiler: xelatex

      # Upload compiled plain PDF for combination job
      - name: Upload compiled plain PDF
        uses: actions/upload-artifact@v4
        with:
          name: temp-plain-pdf
          path: main_plain.pdf
          retention-days: 1
          compression-level: 0

  # Job to create combined PDF artifact (runs after both compilations)
  combine-artifacts:
    runs-on: ubuntu-latest
    needs: [compile, compile-plain]
    steps:
      # Download both compiled PDFs
      - name: Download main PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-main-pdf

      - name: Download plain PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-plain-pdf

      # Upload combined PDF package
      - name: Upload combined PDF package
        uses: actions/upload-artifact@v4
        with:
          name: SummaryZoom-Complete-Package
          path: |
            main.pdf
            main_plain.pdf
          compression-level: 0

  # Job to upload PDF to release (only runs on release events)
  upload-release:
    runs-on: ubuntu-latest
    needs: [compile, compile-plain]
    if: github.event_name == 'release'
    steps:
      # Download the compiled PDFs
      - name: Download main PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-main-pdf

      # Download the compiled plain PDF
      - name: Download plain PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-plain-pdf

      # Upload main PDF to release assets
      - name: Upload PDF to release
        run: gh release upload ${{ github.event.release.tag_name }} ./main.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload plain PDF to release assets
      - name: Upload plain PDF to release
        run: gh release upload ${{ github.event.release.tag_name }} ./main_plain.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
