name: Compile normal and plain PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:
  # Triggers the workflow when a release is created
  #release:
  #  types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to prepare the LaTeX files (convert SVG and modify LaTeX)
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install fonts for LaTeX compilation
      - name: Install fonts for LaTeX compilation
        run: |
          sudo apt update
          sudo apt install -y fonts-liberation ttf-mscorefonts-installer
          # Accept the EULA for MS fonts
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt install -y --reinstall ttf-mscorefonts-installer
          # Update font cache
          sudo fc-cache -f -v
          echo "Fonts installed and ready for LaTeX compilation"

      # Upload prepared files for the compile jobs
      - name: Upload prepared files
        uses: actions/upload-artifact@v4
        with:
          name: prepared-latex-files
          path: |
            main.tex
            main_plain.tex
            sty/
          retention-days: 1
          compression-level: 0

  # Job to compile the LaTeX document
  compile:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      # Download the prepared files
      - name: Download prepared files
        uses: actions/download-artifact@v4
        with:
          name: prepared-latex-files

      # Compile LaTeX document to PDF using XeLaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: lualatex

      # Upload compiled PDF for combination job
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: temp-main-pdf
          path: main.pdf
          retention-days: 1
          compression-level: 0

  # Job to compile the plain LaTeX document (runs in parallel with main compile)
  compile-plain:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      # Download the prepared files
      - name: Download prepared files
        uses: actions/download-artifact@v4
        with:
          name: prepared-latex-files

      # Compile plain LaTeX document to PDF using XeLaTeX
      - name: Compile plain LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main_plain.tex
          compiler: lualatex

      # Upload compiled plain PDF for combination job
      - name: Upload compiled plain PDF
        uses: actions/upload-artifact@v4
        with:
          name: temp-plain-pdf
          path: main_plain.pdf
          retention-days: 1
          compression-level: 0

  # Job to create combined PDF artifact (runs after both compilations)
  combine-artifacts:
    runs-on: ubuntu-latest
    needs: [compile, compile-plain]
    steps:
      # Download both compiled PDFs
      - name: Download main PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-main-pdf

      - name: Download plain PDF
        uses: actions/download-artifact@v4
        with:
          name: temp-plain-pdf

      # Upload combined PDF package
      - name: Upload combined PDF package
        uses: actions/upload-artifact@v4
        with:
          name: SummaryZoom-Complete-Package
          path: |
            main.pdf
            main_plain.pdf
          compression-level: 0


